# Choose a lightweight base image; we provide our own build tools.
language: minimal

# GHC depends on GMP. You can add other dependencies here as well.
addons:
  apt:
    packages:
      - libgmp-dev

# The different configurations we want to test. You could also do things like
# change flags or use --stack-yaml to point to a different file.
env:
  # - ARGS="--resolver ghc.8.10"
  - ARGS="--resolver lts"

before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

# This line installs GHC if necessary, builds the library, executables, and test suites
# `--no-terminal works` around some quirks in Travis's terminal implementation.
install:
  - stack $ARGS --no-terminal --install-ghc test --only-dependencies

# This line runs the test suites.
script:
  - stack $ARGS --no-terminal run infrastructureTest

# Caching so the next build will be fast too.
cache:
  directories:
    - $HOME/.stack
