name:                99problems-tests
version:             0.2.0.0
github:              DavideFauri/99problems-tests
license:             MIT
author:              Davide Fauri
maintainer:          davide.fauri@gmail.com
copyright:           2020 Davide Fauri

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            A test suite for the famous 99 Haskell Problems
category:            Teaching

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/DavideFauri/99problems#readme>

dependencies:
- base >= 4.11 && < 10

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: problems
  dependencies:
    - tasty
    - tasty-hunit
    - tasty-quickcheck

executables:
  99ProblemTests:
    main:                Test.hs
    source-dirs:         test
    dependencies:
    - 99problems-tests
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - tasty-expected-failure

    # ghc-options:
    # - -threaded
    # - -rtsopts
    # - -with-rtsopts=-N
